version: '3'

services:
  # app
  product-service:
    platform: 'linux/amd64'
    image: 'product-service:latest'
    container_name: product-service
    restart: unless-stopped
    build:
      context: product-service
      dockerfile: Dockerfile
    depends_on:
      - master-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://master-db:5432/master_db
      - SPRING_DATASOURCE_USERNAME=irfan
      - SPRING_DATASOURCE_PASSWORD=12345678
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8060
    expose:
      - "8060"
    ports:
      - "8060:8060"
  merchant-service:
    platform: 'linux/amd64'
    image: 'merchant-service:latest'
    container_name: merchant-service
    restart: unless-stopped
    build:
      context: merchant-service
      dockerfile: Dockerfile
    depends_on:
      - master-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://master-db:5432/master_db
      - SPRING_DATASOURCE_USERNAME=irfan
      - SPRING_DATASOURCE_PASSWORD=12345678
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8061
    expose:
      - "8061"
    ports:
      - "8061:8061"
  order-service:
    platform: 'linux/amd64'
    image: 'order-service:latest'
    container_name: order-service
    restart: unless-stopped
    build:
      context: order-service
      dockerfile: Dockerfile
    depends_on:
      - transaksi-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://transaksi-db:5432/transaksi_db
      - SPRING_DATASOURCE_USERNAME=irfan
      - SPRING_DATASOURCE_PASSWORD=12345678
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8062
    expose:
      - "8062"
    ports:
      - "8062:8062"
  rabbitmq-producer-service:
    platform: 'linux/amd64'
    image: 'rabbitmq-producer-service:latest'
    container_name: rabbitmq-producer-service
    build:
      context: rabbitmq-service-producer
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_RABBITMQ_VIRTUAL-host=/
    expose:
      - "8064"
    ports:
      - "8064:8064"
  rabbitmq-consumer-service:
    platform: 'linux/amd64'
    image: 'rabbitmq-consumer-service:latest'
    container_name: rabbitmq-consumer-service
    build:
      context: rabbitmq-service-consumer
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_RABBITMQ_VIRTUAL-host=
    expose:
      - "8063"
    ports:
      - "8063:8063"
  # database & message & cache
  master-db:
    image: 'postgres:15-alpine'
    container_name: master-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=irfan
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=master_db
    volumes:
      - master_db:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5433:5432"
  transaksi-db:
    image: 'postgres:15-alpine'
    container_name: transaksi-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=irfan
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=transaksi_db
    volumes:
      - transaksi_db:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5434:5432"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-local'
    expose:
      - "15672"
      - "5672"
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbit_mq1:/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - rabbit_mq2:/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
volumes:
  master_db:
  transaksi_db:
  rabbit_mq1:
  rabbit_mq2:


