#####Reader endpoint
#insert Reader
POST http://localhost:85/v1/api/readers
Content-Type: application/json

{
  "firstname" : "andika",
  "lastname"  : "wijaya",
  "age"       : 23
}

###
#Get All Reader
GET http://localhost:85/v1/api/readers
Accept: application/json

###
#Get Reader by id
GET http://localhost:85/v1/api/readers/1
Accept: application/json

#####Book End Point
#insert book
POST http://localhost:85/v1/api/books
Content-Type: application/json

{
  "title": "Magic Carpet",
  "page" : 199,
  "year" : "2010"
}

###
#Get All Books
GET http://localhost:85/v1/api/books
Accept: application/json

###
#Get Book by id
GET http://localhost:85/v1/api/books/1
Accept: application/json

###

#update book by id
PUT http://localhost:85/v1/api/books/1
Content-Type: application/json

{
  "title"     : "Magic Carpet Second Edition",
  "page"      : 199,
  "year"      : "2014"
}

###
#update reader by id
PUT http://localhost:85/v1/api/books?id=1&reader_id=2
Content-Type: application/json

###

#Delete Book by id
DELETE http://localhost:85/v1/api/books/1
Accept: application/json

